events/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import EventListView, EventCreateView, EventDetailView, EventDeleteView, EventUpdateView, EventSignupView, MyEventListView, EventRegisteredView,  EventAdminLandingPageView, CheckinCheckoutPhoneInputView, CheckinCheckoutRFIDInputView, EventAdminUserView, CheckinCheckoutUpdateView, event_unregister, switch_teams, set_payment
from django.shortcuts import redirect, render, reverse
from django.http import HttpResponse

app_name = "events"

urlpatterns = [
    path('', EventListView.as_view(), name='event-list'),
    path('<int:pk>/', EventDetailView.as_view(), name = 'event-detail'),
    path('<int:pk>/update/', EventUpdateView.as_view(), name = 'event-update'),
    path('<int:pk>/delete/', EventDeleteView.as_view(), name='event-delete'),
    path('<int:pk>/regsiter/', EventSignupView.as_view(), name='event-signup'),
    path('<int:pk>/regsitered/', EventRegisteredView.as_view(), name='event-registered'),
    path('<int:pk>/registeredDetail', EventDetailView.as_view(), name = 'event-registered-detail'),
    
    path('<int:pk>/unregister/', event_unregister, name='event-unregister'),
    # Path when user tries to Unregister, but is still checked in and has not yet paid!
    path('<int:pk>/unregister_nopay/', event_unregister, name='event-unregister-2'),

    path('create/', EventCreateView.as_view(), name='event-create'),

    path('eventadmin/', EventListView.as_view(), name='event-admin-list'),
    path('eventadmin/<int:pk>/', EventAdminLandingPageView.as_view(), name='event-admin-landing'),
    
    path('eventadmin/<int:pk>/checkincheckoutphone/', CheckinCheckoutPhoneInputView.as_view(), name='checkin-checkout-input-phone'),
    path('eventadmin/<int:pk>/checkincheckoutrfid/', CheckinCheckoutRFIDInputView.as_view(), name='checkin-checkout-input-rfid'),

    
    path('eventmanage/<int:pk>/', EventAdminUserView.as_view(), name='event-manage-user'),
    path('eventmanage/<int:pk>/update', CheckinCheckoutUpdateView.as_view(), name='checkin-checkout-update'),
    path('eventmanage/<int:pk>/switch', switch_teams, name='switch-teams'),
    path('eventmanage/<int:pk>/pay', set_payment, name='set-payment'),

    path('eventmanage/<int:pk>/update-no-pay', CheckinCheckoutUpdateView.as_view(), name='checkin-checkout-update-2'),
    

    path('myevents/', MyEventListView.as_view(), name = 'myevent-list'),
    path('myevents/<int:pk>/', EventDetailView.as_view(), name = 'myevent-detail'),
    path('myevents/<int:pk>/update/', EventUpdateView.as_view(), name = 'myevent-update'),
    path('myevents/<int:pk>/delete/', EventDeleteView.as_view(), name='myevent-delete'),
    
]

gsaEMS/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView
from django.urls import path
from django.urls.conf import include
from users.views import LandingPageView, SignUpView
from .views import AccountSettingsView, ChangePasswordView, UpdateAccountView, AccountDeleteView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('api/', include('rest_framework.urls')),
    path('moderation/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('users/', include('users.urls', namespace='users')),
    path('events/', include('events.urls', namespace='events')),
    path('venues/', include('venues.urls', namespace='venues')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('reset/', PasswordResetView.as_view(), name="resetpass"),
    path('reset/complete', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('reset/done', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    path('settings/', AccountSettingsView.as_view(), name='user-settings'),
    path('settings/changepassword/<int:pk>', ChangePasswordView.as_view(), name='update-password'),
    path('settings/updateinformation/<int:pk>', UpdateAccountView.as_view(), name='update-account'),
    path('settings/deleteaccount/<int:pk>', AccountDeleteView.as_view(), name='delete-account'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import MemberListView, MemberDetailView, MemberUpdateView, MemberDeleteView, MemberListAPI, MemberListAPIDetail, RfidInputView
from django.shortcuts import redirect, render, reverse
from django.http import HttpResponse
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [
    path('', MemberListView.as_view(), name='user-list'),
    
    path('<int:pk>/', MemberDetailView.as_view(), name = 'user-detail'),
    path('<int:pk>/update/', MemberUpdateView.as_view(), name = 'user-update'),
    path('<int:pk>/delete/', MemberDeleteView.as_view(), name='user-delete'),
    path('<int:pk>/rfid/', RfidInputView.as_view(), name='rfid-input'),
    
    # Django-REST Framework
    path('api/', MemberListAPI.as_view()),
    path('api/<int:pk>/', MemberListAPIDetail.as_view())

]

venues/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import VenueListView, VenueDetailView, VenueCreateView, VenueUpdateView, VenueDeleteView, MyVenueListView
from django.shortcuts import redirect, render, reverse
from django.http import HttpResponse

app_name = "venues"

urlpatterns = [
    path('', VenueListView.as_view(), name='venue-list'),
    path('<int:pk>/', VenueDetailView.as_view(), name = 'venue-detail'),
    path('<int:pk>/update/', VenueUpdateView.as_view(), name = 'venue-update'),
    path('<int:pk>/delete/', VenueDeleteView.as_view(), name='venue-delete'),
    path('create/', VenueCreateView.as_view(), name='venue-create'),

    path('venueadmin', VenueListView.as_view(), name='venue-admin-list'),

    path('myvenues/', MyVenueListView.as_view(), name = 'myvenue-list'),
    path('myvenues/<int:pk>/', VenueDetailView.as_view(), name = 'myvenue-detail'),
    path('myvenues/<int:pk>/update/', VenueUpdateView.as_view(), name = 'myvenue-update'),
    path('myvenues/<int:pk>/delete/', VenueDeleteView.as_view(), name='myvenue-delete'),
    
    
   
]

templates/html/event-admin-landing.html

{% extends "base.html" %}

{% block content %}
  <div class="grid grid-cols-1">
    <section class="text-gray-600 body-font">
      <a href="{% url 'events:event-admin-list' %}">Go back</a>
      <hr>
      <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
          {% if request.user.is_superuser %}
         
          
          <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">{{ event.event_title }}</h1>  

         
          <div class="flex justify-center">
            <!--Change-Password-->
            <a href="{% url 'events:checkin-checkout-input-phone' event.pk %}" target="_new">
              <div class="each flex hover:shadow-lg select-none p-10 rounded-md border-gray-300 border mb-3 hover:border-gray-500 cursor-pointer">
              <div class="left">
                  <div class="header text-blue-600 font-semibold text-2xl">Checkin w/ Phone-Number</div>
                  <div class="desc text-gray-600">this is basically used for web based front end designing</div>
              </div>
              <div class="right m-auto mr-0">
                  <div class="icon">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                  </svg>
                  </div>
              </div>
              </div>
            </a>

            <!--Update-Contact-Information-->
            <a href="{% url 'events:checkin-checkout-input-rfid' event.pk%}" target="_new">
              <div class="each flex hover:shadow-lg select-none p-10 rounded-md border-gray-300 border mb-3 hover:border-gray-500 cursor-pointer">
              <div class="left">
                  <div class="header text-blue-600 font-semibold text-2xl">Checkin w/ RFID</div>
                  <div class="desc text-gray-600">this is basically used for web based front end designing</div>
              </div>
              <div class="right m-auto mr-0">
                  <div class="icon">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                  </svg>
                  </div>
              </div>
              </div>
            </a>
          </div>
          
          
          

         
          <table class="table-auto w-full text-left whitespace-no-wrap mt-3">
            <thead>
                <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Player</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Team</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Paid</th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Checkin-Status</th>
                <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
                </tr>
            </thead>
            <tbody>
              
              {%for player in players%}
              <tr>
  
                  {%if player.team is 0%}
                  <td class="px-4 py-3" class="text-blue-900">{{player.user.user.username}}</td>
                  {%else%}
                  <td class="px-4 py-3" class="text-red-900">{{player.user.user.username}}</td>
                  {%endif%}
  
                  {%if player.team is 0%}
                  <td class="px-4 py-3">Blue</td>
                  {%else%}
                  <td class="px-4 py-3">Red</td>
                  {%endif%}
  
                  <td class="px-4 py-3">{{player.is_paid}}</td>
                  <td class="px-4 py-3 text-lg text-gray-900">{{player.is_checkedin}}</td>
                  <td class="w-10 text-center">
                      <a href="{%url 'events:event-manage-user' player.pk %}">
                          <button type="submit" class='text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-1'>Manage</button>
                      </a>
                      
                  </td>
              </tr>
              {%endfor%}
            </tbody>
          </table>
          {%endif%}
      </div>
    </section>
  </div>
 
    

    

    
   
{% endblock content %}

templates/html/event_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
    <a href="{% url 'events:event-list' %}">Go back to Events list</a>
    <hr>
        
    <h1>Create New Event</h1>

    <form method="post">
        <!--{% csrf_token %} used for security purposes and is required for post forms in Django-->
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class='text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-1'>Create</button>
    </form>
{% endblock content %}        
    

templates/html/navbar.html
<!--Header-->
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
<div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
  <div x-data="{ open: false }" class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
    
    <div class="p-4 flex flex-row items-center justify-between">
      <a href="{% url 'landing-page' %}" class="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline">GSA-EMS</a>
      <button class="md:hidden rounded-lg focus:outline-none focus:shadow-outline" @click="open = !open">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-6 h-6">
          <path x-show="!open" fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z" clip-rule="evenodd"></path>
          <path x-show="open" fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
        </svg>
      </button>
    </div>

    <nav :class="{'flex': open, 'hidden': !open}" class="flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
      {% if request.user.is_superuser %}
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'users:user-list' %}">Users</a>
      {% endif %}

      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'events:event-list' %}">Events</a>
      
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'venues:venue-list' %}">Venues</a>



      {% if request.user.is_authenticated %}
      <a class = "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'events:event-registered' request.user.pk %}">Registered-Events</a>
      {% endif %}

      {% if request.user.is_superuser %}
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'admin:index' %}" >View-Dashboard</a>
      {% endif %}

      {% if request.user.is_superuser and request.user.is_authenticated %}
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'events:event-admin-list'%}">Manage-Events</a>
      {% endif %}

      {% if request.user.is_superuser and request.user.is_authenticated %}
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'venues:venue-admin-list'%}">Manage-Venues</a>
      {% endif %}
      
      {% if request.user.is_authenticated %}
      <a class = "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'user-settings' %}">Settings</a>
      {% endif %}

      {% if request.user.is_authenticated %}
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'logout' %}">
        Logout
      </a>
      {% endif %}
      {% if not request.user.is_authenticated %}
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'signup' %}">
        Sign Up
      </a>
      <a class="px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" href="{% url 'login' %}">
        Log in
      </a>

      {% endif %}
      

    </nav>
  </div>

  
</div>



<!--<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">
          <a href="{% url 'landing-page' %}">GSA EMS</a>
        </span>
      </a>

      <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
        
        {% if request.user.is_superuser %}
        <a href="{% url 'users:user-list' %}" class="mr-5 hover:text-gray-900">Users</a>
        {% endif %}

        <a href="{% url 'events:event-list' %}" class="mr-5 hover:text-gray-900">Events</a>
        
        <a href="{% url 'venues:venue-list' %}" class="mr-5 hover:text-gray-900">Venues</a>


        {% if request.user.is_superuser %}
        <a href="{% url 'admin:index' %}" class="mr-5 hover:text-gray-900">Admin</a>
        {% endif %}
        
      </nav>

      {% if request.user.is_authenticated %}
      <a href="{% url 'events:event-registered' request.user.pk %}" class="mr-5 hover:text-gray-900">Registered-Events</a>
     

      {% if request.user.is_superuser and request.user.is_authenticated %}
      <a href="{% url 'events:event-admin-list'%}" class="mr-5 hover:text-gray-900">Manage-Events</a>
      {% endif %}
   
      You are logged in as {{ request.user.username }}
      <a href="{% url 'logout' %}">
        <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base ml-4 mt-4 md:mt-0">Log out
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </button>
      </a>
      
      {% endif %}
      {% if not request.user.is_authenticated %}
      <a href="{% url 'signup' %}">
        <button class="inline-flex items-center border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Sign Up
        </button>  
      </a>
      <a href="{% url 'login' %}">
        <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Log in
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </button>  
      </a>

      {% endif %}
    </div>
</header>-->


templates/html/user_detail.html
{% extends "base.html" %}

{% block content %}


    <a href="{% url 'users:user-list' %}">Go back to User-list</a>
    <hr>

    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">User</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{ lead.firstname }} {{ lead.lastname }} </h1>

                <div class="flex mb-4">
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
                </div>

                <p class="leading-relaxed mb-4">A User Profile.</p>

                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Username</span>
                    <span class="ml-auto text-gray-900">{{ user.user.username }}</span>
                </div>

                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">RFID:</span>
                    <span class="ml-auto text-gray-900">{{ user.rfid }}</span>
                </div>

                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Full Name:</span>
                    <span class="ml-auto text-gray-900">{{ user.user.first_name }} {{ user.user.last_name }}</span>
                </div>
                
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Email:</span>
                    <span class="ml-auto text-gray-900">{{ user.user.email }}</span>
                </div>

            
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Telephone-Number:</span>
                    <span class="ml-auto text-gray-900">{{ user.user.phone_number }}</span>
                </div>
                
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">is_blacklist:</span>
                    <span class="ml-auto text-gray-900">{{ user.user.is_blacklist }}</span>
                </div>

                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">is_organizer:</span>
                    <span class="ml-auto text-gray-900">{{ user.user.is_blacklist }}</span>
                </div>

                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">is_regular:</span>
                    <span class="ml-auto text-gray-900">{{ user.user.is_regular }}</span>
                </div>

                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">is_beginner:</span>
                    <span class="ml-auto text-gray-900">{{ user.user.is_beginner }}</span>
                </div>

                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Organization:</span>
                    <span class="ml-auto text-gray-900">{{ user.user.organisation_name }}</span>
                </div>
            
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
            
            <div class="flex">
                {% if request.user.is_superuser %}
                <a href="{%url 'users:user-update' user.pk %}"><button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded">Update</button></a>
                
                <a href="{%url 'users:user-delete' user.pk %}"><button class="flex ml-4 text-white bg-indigo-500 border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded">Delete</button></a>
                

                <a href="{%url 'users:rfid-input' user.pk %}"><button class="flex ml-4 text-white bg-indigo-500 border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded">Update-RFID</button></a>
                {% endif %}
            </div>
            
        </div>
        </div>
    </section>
       
    <script src="" async defer></script>

{% endblock content %}